version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn fastapi_asgi:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./backend_fastapi:/usr/src/app
    ports:
      - 5001:8000
    extra_hosts:
        - "localhost:host-gateway"
